/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/agents/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Declare a completed run (agent manifest POST)
         * @description A measurement-PC agent POSTs the run manifest to declare completion. Authenticated with X-Agent-Id + X-Agent-Key. Idempotent on run_id: a duplicate POST returns the existing run without re-enqueuing work.
         */
        post: operations["agent-post-manifest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Obtain an access token
         * @description Verifies email and password; returns a short-lived JWT access token.
         */
        post: operations["auth-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user profile
         * @description Returns the profile of the currently authenticated user.
         */
        get: operations["auth-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user account
         * @description Creates a new human reviewer account. In development the account is immediately active; in production it requires admin activation.
         */
        post: operations["auth-register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List runs awaiting review
         * @description Returns runs in state awaiting_review with their latest review_artifact summary.
         */
        get: operations["reviews-list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get review bundle
         * @description Returns the run, latest review_artifact, files, and transitions.
         */
        get: operations["reviews-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/{run_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a run
         * @description Transitions awaiting_review→approved, records decision, and enqueues publish_run.
         */
        post: operations["reviews-approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/{run_id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Correct operator comment
         * @description Identity/display correction (§9): updates runs.operator_comment without changing state.
         */
        patch: operations["reviews-patch-metadata"];
        trace?: never;
    };
    "/v1/reviews/{run_id}/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quarantine a run
         * @description Transitions awaiting_review→quarantined and records decision with reason.
         */
        post: operations["reviews-quarantine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/{run_id}/request-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request changes on a run
         * @description Transitions awaiting_review→changes_requested and records decision with reason.
         */
        post: operations["reviews-request-changes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List runs
         * @description Browse/search runs by state, sample, device, measurement type, or agent. Newest first.
         */
        get: operations["runs-list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a run
         * @description Returns a run with its verified raw files and full state-transition audit trail.
         */
        get: operations["runs-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthLoginInputBody_663e576b: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/AuthLoginInputBody_663e576b.json
             */
            readonly $schema?: string;
            /** @description User email address */
            email: string;
            /** @description Password */
            password: string;
        };
        AuthLoginOutputBody_ece96b00: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/AuthLoginOutputBody_ece96b00.json
             */
            readonly $schema?: string;
            access_token: string;
            /**
             * Format: int64
             * @description Seconds until the token expires
             */
            expires_in: number;
            token_type: string;
            user: components["schemas"]["UserProfile"];
        };
        AuthMeOutputBody_1b20e166: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/AuthMeOutputBody_1b20e166.json
             */
            readonly $schema?: string;
            user: components["schemas"]["UserProfile"];
        };
        AuthRegisterInputBody_3a2b514b: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/AuthRegisterInputBody_3a2b514b.json
             */
            readonly $schema?: string;
            /** @description Human-readable display name */
            display_name: string;
            /** @description User email address */
            email: string;
            /** @description Password (min 8 characters) */
            password: string;
        };
        AuthRegisterOutputBody_f5e4d292: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/AuthRegisterOutputBody_f5e4d292.json
             */
            readonly $schema?: string;
            user_id: string;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /** @description Machine-readable error code, e.g. sample.not_found */
            code: string;
            /** @description Optional structured detail */
            details?: {
                [key: string]: unknown;
            };
            /** @description Human-readable error message */
            message: string;
        };
        GetRunOutputBody_87da3ba3: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/GetRunOutputBody_87da3ba3.json
             */
            readonly $schema?: string;
            files: components["schemas"]["RunFile"][] | null;
            run: components["schemas"]["Run"];
            transitions: components["schemas"]["RunStateTransition"][] | null;
        };
        ListRunsOutputBody_9b02742d: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ListRunsOutputBody_9b02742d.json
             */
            readonly $schema?: string;
            runs: components["schemas"]["Run"][] | null;
        };
        Manifest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/Manifest.json
             */
            readonly $schema?: string;
            agent_id: string;
            archive: components["schemas"]["ManifestArchive"];
            completion_source: string;
            condition_labels: string[] | null;
            contact_config_id: string;
            /** Format: date-time */
            declared_at: string;
            declared_by: string;
            device_id: string;
            files: components["schemas"]["ManifestFile"][] | null;
            instrument_json: string;
            meas_path: string;
            measurement_type: string;
            operator_comment: string;
            param_versions: {
                [key: string]: number;
            };
            run_id: string;
            sample_id: string;
            /** Format: int64 */
            schema_version: number;
        };
        ManifestArchive: {
            name: string;
            sha256: string;
        };
        ManifestFile: {
            /** Format: int64 */
            bytes: number;
            name: string;
            sha256: string;
        };
        ManifestOutputBody_3f7000f3: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ManifestOutputBody_3f7000f3.json
             */
            readonly $schema?: string;
            /** @description true if this POST declared a new run; false if it already existed */
            created: boolean;
            run_id: string;
            state: string;
        };
        ReviewApproveOutputBody_7d680067: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ReviewApproveOutputBody_7d680067.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            decision_id: number;
            /** Format: int64 */
            job_id: number;
            run_id: string;
            state: string;
        };
        ReviewArtifactFull: {
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            id: number;
            llm_summary: string;
            metrics_json: unknown;
            parser_warnings_json: unknown;
            plots_json: unknown;
            run_id: string;
            summary_json: unknown;
            /** Format: int64 */
            version: number;
        };
        ReviewArtifactSummary: {
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            id: number;
            llm_summary: string;
            metrics_json: unknown;
            parser_warnings_json: unknown;
            /** Format: int64 */
            version: number;
        };
        ReviewGetOutputBody_b610a7a6: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ReviewGetOutputBody_b610a7a6.json
             */
            readonly $schema?: string;
            files: components["schemas"]["RunFile"][] | null;
            latest_artifact?: components["schemas"]["ReviewArtifactFull"];
            run: components["schemas"]["Run"];
            transitions: components["schemas"]["RunStateTransition"][] | null;
        };
        ReviewListItem: {
            latest_artifact?: components["schemas"]["ReviewArtifactSummary"];
            run: components["schemas"]["Run"];
        };
        ReviewListOutputBody_9a2fb657: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ReviewListOutputBody_9a2fb657.json
             */
            readonly $schema?: string;
            reviews: components["schemas"]["ReviewListItem"][] | null;
        };
        ReviewPatchMetadataInputBody_8af97060: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ReviewPatchMetadataInputBody_8af97060.json
             */
            readonly $schema?: string;
            operator_comment: string;
        };
        ReviewPatchMetadataOutputBody_e4cbab6f: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ReviewPatchMetadataOutputBody_e4cbab6f.json
             */
            readonly $schema?: string;
            operator_comment: string;
            run_id: string;
        };
        ReviewQuarantineInputBody_460594ef: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ReviewQuarantineInputBody_460594ef.json
             */
            readonly $schema?: string;
            reason: string;
        };
        ReviewQuarantineOutputBody_54d47f73: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ReviewQuarantineOutputBody_54d47f73.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            decision_id: number;
            run_id: string;
            state: string;
        };
        ReviewRequestChangesInputBody_460594ef: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ReviewRequestChangesInputBody_460594ef.json
             */
            readonly $schema?: string;
            reason: string;
        };
        ReviewRequestChangesOutputBody_54d47f73: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ReviewRequestChangesOutputBody_54d47f73.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            decision_id: number;
            run_id: string;
            state: string;
        };
        Run: {
            agent_id: string;
            completion_source: string;
            contact_config_id?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            declared_at: string;
            declared_by: string;
            device_id?: string;
            id: string;
            manifest_hash: string;
            meas_path: string;
            measurement_type: string;
            operator_comment: string;
            sample_id?: string;
            state: string;
            /** Format: date-time */
            updated_at: string;
        };
        RunFile: {
            /** Format: int64 */
            bytes: number;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            id: number;
            name: string;
            run_id: string;
            sha256: string;
        };
        RunStateTransition: {
            actor_id: string;
            actor_type: string;
            /** Format: date-time */
            created_at: string;
            from_state: string;
            /** Format: int64 */
            id: number;
            payload_json?: unknown;
            reason: string;
            run_id: string;
            to_state: string;
        };
        UserProfile: {
            display_name: string;
            email: string;
            global_role: string;
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "agent-post-manifest": {
        parameters: {
            query?: never;
            header?: {
                /** @description Agent identifier (matches agents.id) */
                "X-Agent-Id"?: string;
                /** @description Agent shared key */
                "X-Agent-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Manifest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManifestOutputBody_3f7000f3"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "auth-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginInputBody_663e576b"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthLoginOutputBody_ece96b00"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "auth-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeOutputBody_1b20e166"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "auth-register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRegisterInputBody_3a2b514b"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthRegisterOutputBody_f5e4d292"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "reviews-list": {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListOutputBody_9a2fb657"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "reviews-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewGetOutputBody_b610a7a6"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "reviews-approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewApproveOutputBody_7d680067"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "reviews-patch-metadata": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewPatchMetadataInputBody_8af97060"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPatchMetadataOutputBody_e4cbab6f"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "reviews-quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewQuarantineInputBody_460594ef"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQuarantineOutputBody_54d47f73"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "reviews-request-changes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequestChangesInputBody_460594ef"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRequestChangesOutputBody_54d47f73"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "runs-list": {
        parameters: {
            query?: {
                state?: string;
                sample_id?: string;
                device_id?: string;
                measurement_type?: string;
                agent_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRunsOutputBody_9b02742d"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "runs-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRunOutputBody_87da3ba3"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
